import re, math
from PIL import Image

def parse_path(d):
    toks = re.findall(r'[MmLlHhVvQqTtCcZz]|-?\d*\.?\d+', d)
    i=0; cmd=None; cx=cy=0; sx=sy=0; subs=[]; cur=[]; prevc=None; pqx=pqy=0
    def num():
        nonlocal i; v=float(toks[i]); i+=1; return v
    while i < len(toks):
        t=toks[i]
        if re.match(r'[A-Za-z]', t): cmd=t; i+=1
        rel=cmd.islower(); C=cmd.upper()
        if C=='M':
            x=num();y=num()
            if rel:x+=cx;y+=cy
            if cur:subs.append(cur)
            cur=[(x,y)];cx,cy=x,y;sx,sy=x,y;cmd='l' if rel else 'L';prevc='M'
        elif C=='L':
            x=num();y=num()
            if rel:x+=cx;y+=cy
            cur.append((x,y));cx,cy=x,y;prevc='L'
        elif C=='H':
            x=num()
            if rel:x+=cx
            cur.append((x,cy));cx=x;prevc='H'
        elif C=='V':
            y=num()
            if rel:y+=cy
            cur.append((cx,y));cy=y;prevc='V'
        elif C=='Q':
            x1=num();y1=num();x=num();y=num()
            if rel:x1+=cx;y1+=cy;x+=cx;y+=cy
            for s in range(1,11):
                tt=s/10.0;mx=(1-tt)**2*cx+2*(1-tt)*tt*x1+tt*tt*x;my=(1-tt)**2*cy+2*(1-tt)*tt*y1+tt*tt*y
                cur.append((mx,my))
            pqx,pqy=x1,y1;cx,cy=x,y;prevc='Q'
        elif C=='T':
            x=num();y=num()
            if rel:x+=cx;y+=cy
            if prevc in('Q','T'):x1=2*cx-pqx;y1=2*cy-pqy
            else:x1,y1=cx,cy
            for s in range(1,11):
                tt=s/10.0;mx=(1-tt)**2*cx+2*(1-tt)*tt*x1+tt*tt*x;my=(1-tt)**2*cy+2*(1-tt)*tt*y1+tt*tt*y
                cur.append((mx,my))
            pqx,pqy=x1,y1;cx,cy=x,y;prevc='T'
        elif C=='C':
            x1=num();y1=num();x2=num();y2=num();x=num();y=num()
            if rel:x1+=cx;y1+=cy;x2+=cx;y2+=cy;x+=cx;y+=cy
            for s in range(1,13):
                tt=s/12.0;mx=(1-tt)**3*cx+3*(1-tt)**2*tt*x1+3*(1-tt)*tt*tt*x2+tt**3*x
                my=(1-tt)**3*cy+3*(1-tt)**2*tt*y1+3*(1-tt)*tt*tt*y2+tt**3*y
                cur.append((mx,my))
            cx,cy=x,y;prevc='C'
        elif C=='Z':
            if cur:subs.append(cur);cur=[]
            cx,cy=sx,sy;prevc='Z'
        else:i+=1
    if cur:subs.append(cur)
    return subs

def rasterize(d,size=48,ss=4,vb=(0,-960,960,960)):
    W=H=size*ss;vx,vy,vw,vh=vb
    polys=[[((px-vx)/vw*W,(py-vy)/vh*H) for px,py in s] for s in parse_path(d)]
    img=Image.new('L',(W,H),0);px=img.load();edges=[]
    for poly in polys:
        n=len(poly)
        for k in range(n):
            x0,y0=poly[k];x1,y1=poly[(k+1)%n]
            if y0!=y1: edges.append((x0,y0,x1,y1))
    for y in range(H):
        yc=y+0.5;xs=[]
        for x0,y0,x1,y1 in edges:
            if (y0<=yc<y1) or (y1<=yc<y0):
                t=(yc-y0)/(y1-y0);xs.append((x0+t*(x1-x0),1 if y1>y0 else -1))
        xs.sort();wn=0
        for idx in range(len(xs)-1):
            wn+=xs[idx][1]
            if wn!=0:
                xa=int(math.ceil(xs[idx][0]-0.5));xb=int(math.floor(xs[idx+1][0]-0.5))
                for x in range(max(0,xa),min(W-1,xb)+1):px[x,y]=255
    return img.resize((size,size),Image.LANCZOS)

SIZE=48
names=['menu','light','color','shadow','ground','performance']
out=[]
out.append("// SPDX-License-Identifier: MIT")
out.append("// GENERATED by tools/gen_icons (do not edit). Rasterized from Icons/icon_*.svg")
out.append("// (Antho's Material-style icons) into white+alpha RGBA, %dx%d, for ImGui textures." % (SIZE,SIZE))
out.append("// Re-generate after changing the SVGs; see the AR20 Spec Change Log.")
out.append("#pragma once")
out.append("namespace rav {")
out.append("constexpr int kIconSize = %d;" % SIZE)
for nm in names:
    svg=open(f'Icons/icon_{nm}.svg').read()
    d=re.search(r'd="([^"]+)"',svg).group(1)
    img=rasterize(d,SIZE)
    a=img.load()
    # RGBA white + alpha
    data=[]
    for y in range(SIZE):
        for x in range(SIZE):
            cov=a[x,y]
            data += [255,255,255,cov]
    body=",".join(str(v) for v in data)
    out.append(f"// icon_{nm}.svg")
    out.append(f"inline const unsigned char kIcon_{nm}[%d*%d*4] = {{{body}}};" % (SIZE,SIZE))
out.append("}  // namespace rav")
open("src/overlay_icons.h","w").write("\n".join(out)+"\n")
print("wrote src/overlay_icons.h", "bytes:", len("\n".join(out)))
